name: CD

on:
  workflow_run:
    workflows: [ "CI pipeline" ]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build and push my Docker image
        run: |
          docker build -t 0xnickm/mars-weather-report:${{ github.sha }} .
          docker push 0xnickm/mars-weather-report:${{ github.sha }}
