# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI pipeline

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  linting-unit:
    runs-on: ubuntu-latest
  
    permissions:
      checks: write
  
    steps:
    - uses: actions/checkout@v4
  
    - name: Build Docker image
      run: docker build -t mars-weather-report .
  
    - name: Lint inside container
      run: docker run --rm mars-weather-report flake8 . --exit-zero
  
    - name: Run unit tests inside container and generate JUnit report
      run: |
        mkdir -p reports
        docker run --rm -u root -v ${{ github.workspace }}/reports:/app/reports mars-weather-report pytest -v tests/unit --junitxml=/app/reports/Unit_Test-results.xml
  
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: 'reports/Unit_Test-results.xml'
        detailed_summary: true
        include_passed: true

  integration:
    # os of the runner
    runs-on: ubuntu-latest

    permissions:
      checks: write
      
    # this job depends on the previous job (linting-unit)
    needs: linting-unit
    
    steps:
    # takes the code from the repo
    - uses: actions/checkout@v4

    # build the Docker image from the Dockerfile and call it mars-weather-report
    - name: build the Docker image
      run: docker build -t mars-weather-report .

    # run integration tests using pytest inside the container
    - name: run unit tests inside container and generate JUnit report
      run: |
        mkdir -p reports
        docker run --rm -u root -v ${{ github.workspace }}/reports:/app/reports mars-weather-report pytest -v tests/integration --junitxml=/app/reports/Integration_Test-results.xml
  
    - name: publish Integration Tests Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: 'reports/Integration_Test-results.xml'
        detailed_summary: true
        include_passed: true
