# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push

permissions:
  contents: read

jobs:
  linting-unit:
    # os of the runner
    runs-on: ubuntu-latest
    env:
      NASA_API_KEY: ${{secrets.NASA_API_KEY}}

    steps:
    # takes the code
    - uses: actions/checkout@v4

    # build the docker image using the docker-compose.yml file
    - name: Build Docker images
      run: docker compose build

    # run flake8 (linting) inside the service container
    - name: Lint inside container
      run: docker compose run --rm mars-weather-report flake8 . --exit-zero

    # run unit tests using pytest inside the service container
    - name: Run unit tests inside container
      run: docker compose run --rm --user root mars-weather-report pytest tests/unit

  integration:
    # os of the runner
    runs-on: ubuntu-latest
    env:
      NASA_API_KEY: ${{secrets.NASA_API_KEY}}
    needs: linting-unit

    steps:
    # takes the code
    - uses: actions/checkout@v4

    # build the docker image using the docker-compose.yml file
    - name: Build Docker images
      run: docker compose build

    # run integration tests using pytest inside the service container
    - name: Run unit tests inside container
      run: docker compose run --rm mars-weather-report pytest tests/unit
  
